---
# Template configuration files for npm

- name: template is copied
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  become: true
  loop: "{{ npm_templates_copy }}"
  when: npm_copy_templates
